repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix
        name: Markdownlint Fix
        description: Fix markdown lint issues automatically
        args: ['--config', '.markdownlint.json']
